name: CI for Oasees-sdk

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  k3s-cluster-init:
    runs-on: oasees-sdk-master
    outputs:
      output1: ${{ steps.token.outputs.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check oasees-sdk cli
        run: oasees-sdk --help

      - name: Get cluster token
        id: token
        run: echo "token=$(echo $(oasees-sdk get-token))" >> "$GITHUB_OUTPUT" 

  add-worker:
    runs-on: oasees-sdk-worker
    needs: k3s-cluster-init
    steps:
      - env:
          OUTPUT1: ${{needs.k3s-cluster-init.outputs.output1}}
        name: Join cluster
        run: echo "$OUTPUT1"
        # run: oasees-sdk join-cluster --ip 10.0.19.182 --token $OUTPUT1

  test-cluster:
    runs-on: oasees-sdk-master
    needs: add-worker
    steps:
        - name: test cluster
          run: echo "$(kubectl get nodes)"

        - name: uninstall master
          run: oasees-sdk uninstall master

  uninstall-worker:
    runs-on: oasees-sdk-worker
    needs: k3s-cluster-init
    steps:
      - name: uninstall worker
        run: oasees-sdk uninstall agent

